# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NYTimee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NYTimee 
  # Pod for Reactive Programming
  pod 'RxSwift'
  pod 'RxCocoa'
  
  # Pod for networking
  pod 'Alamofire'
  
  # Pod for parsing
  pod 'SwiftyJSON'
  
  # Pod for loading
  pod 'MBProgressHUD'
  
  # Pod for images
  pod 'Kingfisher'

  target 'NYTimeeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NYTimeeUITests' do
    # Pods for testing
  end

end
